
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: databaseName
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=databaseName;Username=dbuser;Password=dbpassword
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network


volumes:
  db_data:

networks:
  app-network:
    driver: bridge
