# Utilizar la ultoma imagen oficial de PostgreSQL como base
FROM postgres:latest

# Establecer variables de entorno para la configuración de PostgreSQL
ENV POSTGRES_USER=dbuser
ENV POSTGRES_PASSWORD=dbpassword
ENV POSTGRES_DB=MyDaBase

# Exponer el puerto por defecto de PostgreSQL
EXPOSE 5432
